- package-lock.json
- package.json
> chore: make repo commitizen friendly

- packages/ci-context/src/lib/context.factory.ts
- packages/ci-context/src/lib/repo.factory.ts
- packages/ci-context/src/lib/utils/jenkins.spec.ts
- packages/ci-context/src/lib/utils/jenkins.ts
Provide context for Jenkins CI
> feat(ci-context): jenkins context

- packages/nx-docker/README.md
Fixes link  `Push to Mulitple Registries` [Push to multi-registries](docs/advanced/push-multiple-registries.md)
> Update broken link

- package-lock.json
- package.json
- packages/ci-context/package.json
- packages/container-metadata/package.json
- packages/core/package.json
- packages/nx-container/package.json
- packages/nx-container/src/executors/build/executor.ts
- packages/nx-prisma/package.json
- packages/nx-set-shas/package.json
> fix(nx-container): fix command evn variable interpolation

- package-lock.json
- package.json
- packages/ci-context/src/lib/context.factory.ts
- packages/ci-context/src/lib/repo.factory.ts
- packages/ci-context/src/lib/utils/teamcity-helpers.ts
- packages/ci-context/src/lib/utils/teamcity.spec.ts
- packages/ci-context/src/lib/utils/teamcity.ts
> feat(ci-context): support teamcity

- package-lock.json
- package.json
- packages/ci-context/package.json
- packages/container-metadata/package.json
- packages/core/package.json
- packages/nx-container/package.json
- packages/nx-prisma/package.json
- packages/nx-set-shas/package.json
drop support for Nx 12 and 13
BREAKING CHANGE: drop support for Nx 12 and 13
> chore: prepare release 5.0.0-alpha.1

- packages/nx-container/docs/inputs.md
This one took me a while ... Would be nice if you merge my doc fix so the next person falling into this pit won't get stuck as long as i did.
> Add note to replace dashes with unterscores in INPUT env variables

- packages/nx-prisma/README.md
- packages/nx-prisma/executors.json
- packages/nx-prisma/src/executors/validate/executor.spec.ts
- packages/nx-prisma/src/executors/validate/executor.ts
- packages/nx-prisma/src/executors/validate/schema.d.ts
- packages/nx-prisma/src/executors/validate/schema.json
Add the `prisma validate` command as an executor
> Add Prisma validate executor

- packages/nx-prisma/package.json
- packages/nx-prisma/src/generators/init/generator.ts
- packages/nx-prisma/src/generators/init/lib/add-prisma-config.ts
- packages/nx-prisma/src/generators/init/lib/detect-prisma-installed-version.ts
- packages/nx-prisma/src/generators/init/utils/versions.ts
> feat(nx-prisma): initial support for prisma 5

- package-lock.json
- package.json
- packages/nx-prisma/.eslintrc.json
- packages/nx-prisma/package.json
- packages/nx-prisma/src/executors/seed/executor.spec.ts
- packages/nx-prisma/src/executors/seed/executor.ts
- packages/nx-prisma/src/executors/seed/schema.d.ts
- packages/nx-prisma/src/executors/seed/schema.json
Port of https://github.com/gperdomor/nx-tools/pull/989 to the v5.0 branch.
> feat(nx-prisma): allow to execute seeding script with `tsx`

- packages/nx-container/src/executors/build/engines/docker/docker.engine.spec.ts
- packages/nx-container/src/executors/build/engines/docker/docker.engine.ts
This resolves: 
- https://github.com/gperdomor/nx-tools/issues/1023
> fix(nx-container): provenance 'false' ignored

- packages/nx-prisma/src/executors/generate/executor.ts
- packages/nx-prisma/src/executors/generate/schema.d.ts
- packages/nx-prisma/src/executors/generate/schema.json
This PR adds support for supporting the generator to use for generator the prisma client.
https://www.prisma.io/docs/orm/prisma-schema/overview/generators
> feat: add generator flag support to specify generator

- packages/core/src/lib/get-input-list.spec.ts
- packages/core/src/lib/get-input-list.ts
fix issue getting prefixed variables for lists
fix #1045
> fix(core): fix issue getting prefixed variables

- packages/nx-container/README.md
- packages/nx-prisma/README.md
> docs: fix nx-container and nx-prisma setup docs

- plugins/nx-graphql-codegen/README.md
Fix doc issue with setup command
fix #1062
> docs(nx-graphql-codegen): fix generator setup command

- packages/container-metadata/package.json
- packages/container-metadata/src/lib/context.spec.ts
- packages/container-metadata/src/lib/context.ts
- packages/container-metadata/src/lib/flavor.spec.ts
- packages/container-metadata/src/lib/flavor.ts
- packages/container-metadata/src/lib/image.spec.ts
- packages/container-metadata/src/lib/image.ts
- packages/container-metadata/src/lib/main.ts
- packages/container-metadata/src/lib/meta.spec.ts
- packages/container-metadata/src/lib/meta.ts
- packages/container-metadata/src/lib/tag.spec.ts
- packages/container-metadata/src/lib/tag.ts
- plugins/nx-container/package.json
- plugins/nx-container/src/executors/build/executor.ts
- plugins/nx-container/src/generators/configuration/generator.spec.ts
Closes https://github.com/gperdomor/nx-tools/issues/1099
> feat(nx-container): forward quiet option to metadata generation for quiet logs

- plugins/nx-prisma/src/generators/configuration/constants.ts
> fix(nx-prisma): Upgraded prisma version

- plugins/nx-container/src/executors/build/executor.ts
> chore: Wrap engine exec in logs group

- plugins/nx-container/README.md
Fixed advanced documentation links
fix #1162
> docs(nx-container): fix documentation links

- .github/workflows/publish.yml
- nx.json
- package-lock.json
- packages/ci-context/package.json
- packages/container-metadata/package.json
- packages/core/package.json
- packages/nx-set-shas/package.json
- plugins/nx-container/package.json
- plugins/nx-graphql-codegen/package.json
- plugins/nx-prisma/package.json
This PR adds NPM provenance support and change the release versioning to used fixed releases
> feat: fixed releases and provenance support

- packages/ci-context/package.json
- packages/ci-context/project.json
- packages/ci-context/tsconfig.lib.json
- packages/ci-context/tsconfig.spec.json
- packages/ci-context/vite.config.ts
> feat(ci-context): updated config files to align with new library generators

- packages/container-metadata/package.json
- packages/container-metadata/project.json
- packages/container-metadata/tsconfig.lib.json
- packages/container-metadata/tsconfig.spec.json
- packages/container-metadata/vite.config.ts
> feat(container-metadata): updated config files to align with new library generators

- plugins/nx-container/package.json
- plugins/nx-container/tsconfig.json
- plugins/nx-container/vite.config.ts
> feat(nx-container): updated config files to align with new plugin generator

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
> ci: update codeql workflow

- .github/workflows/ci.yml
- .gitlab-ci.yml
- .husky/commit-msg
- .husky/post-checkout
- .husky/post-merge
- .husky/pre-commit
- .husky/pre-push
- .lintstagedrc.json
- .npmrc
- lefthook.yml
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- tsconfig.base.json
> feat: replace husky with lefthook
